In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
# read the csv files into pandas as dataframes
filepath = os.path.join("..","raw_data/wineData.csv")
wine_df = pd.read_csv(filepath,encoding="iso-8859-1", low_memory=False)

FileNotFoundError: File b'..\\raw_data/wineData.csv' does not exist

In [48]:
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
1,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
2,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
3,10,US,"Soft, supple plum envelopes an oaky structure ...",Mountain Cuvée,87,19.0,California,Napa Valley,Napa,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
4,12,US,"Slightly reduced, this wine offers a chalky, t...",NaN,87,34.0,California,Alexander Valley,Sonoma,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini

In [49]:
wine_df = wine_df[wine_df.region_1!= ""]

In [50]:
wine_df.count()

Unnamed: 0               50457
country                  50457
description              50457
designation              34170
points                   50457
price                    50238
province                 50457
region_1                 50202
region_2                 46769
taster_name              34466
taster_twitter_handle    31749
title                    50457
variety                  50457
winery                   50457
dtype: int64

In [51]:
wine_df = wine_df.drop(['region_2','designation','Unnamed: 0'],axis=1)

In [52]:
wine_df.count()

country                  50457
description              50457
points                   50457
price                    50238
province                 50457
region_1                 50202
taster_name              34466
taster_twitter_handle    31749
title                    50457
variety                  50457
winery                   50457
dtype: int64

In [53]:
wine_df.dropna()

,country,description,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery
0,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
2,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
3,US,"Soft, supple plum envelopes an oaky structure ...",87,19.0,California,Napa Valley,Virginie Boone,@vboone,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature
4,US,"Slightly reduced, this wine offers a chalky, t...",87,34.0,California,Alexander Valley,Virginie Boone,@vboone,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini
5,US,Building on 150 years and six generations of w...,87,12.0,California,Central Coast,Matt Kettmann,@mattkettmann,Mirassou 2012 Chardonnay (Central Coast),Chardonnay,Mirassou
8,US,"A sleek mix of tart berry, stem and herb, alon...",87,20.0,Oregon,Oregon,Paul Gregutt,@paulgwine,Acrobat 2013 Pinot Noir (Oregon),Pinot Noir,Acrobat
9,US,This wine from the Geneseo district offers aro...,87,22.0,California,Paso Robles,Matt Kettmann,@mattkettmann,Bianchi 2011 Signature Selection Merlot (Paso ...,Merlot,Bianchi
10,US,Oak and earth intermingle around robust aromas...,87,69.0,California,Sonoma Coast,Virginie Boone,@vboone,Castello di Amorosa 2011 King Ridge Vineyard P...,Pinot Noir,Castello di Amorosa
11,US,Clarksburg is becoming a haven for Chenin Blan...,86,16.0,California,Clarksburg,Virginie Boone,@vboone,Clarksburg Wine Company 2010 Chenin Blanc (Cla...,Chenin Blanc,Clarksburg Wine Company
14,US,As with many of the Erath 2010 vineyard design...,86,50.0,Oregon,McMinnville,Paul Gregutt,@paulgwine,Erath 2010 Hyland Pinot Noir (McMinnville),Pinot Noir,Erath
15,US,"A stiff, tannic wine, this slowly opens and br...",86,22.0,Oregon,Willamette Valley,Paul Gregutt,@paulgwine,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars
21,US,"This is weighty, creamy and medium to full in ...",85,14.0,California,North Coast,Virginie Boone,@vboone,Souverain 2010 Chardonnay (North Coast),Chardonnay,Souverain
22,US,"Aromas of cranberry, barrel spice and herb are...",86,55.0,Washington,Columbia Valley (WA),Sean P. Sullivan,@wawinereport,Mellisoni 2014 Malbec (Columbia Valley (WA)),Malbec,Mellisoni
23,US,"Syrupy and dense, this wine is jammy in plum a...",86,100.0,California,Napa Valley,Virginie Boone,@vboone,Okapi 2013 Estate Cabernet Sauvignon (Napa Val...,Cabernet Sauvignon,Okapi
24,US,"The aromas are brooding, with notes of barrel ...",86,25.0,Washington,Columbia Valley (WA),Sean P. Sullivan,@wawinereport,Ram 2014 Alder Ridge Vineyard Cabernet Franc (...,Cabernet Franc,Ram
25,US,There are intriguing touches to the nose of th...,86,26.0,California,Santa Ynez Valley,Matt Kettmann,@mattkettmann,Sevtap 2015 Golden Horn Sauvignon Blanc (Santa...,Sauvignon Blanc,Sevtap
26,US,"A blend of Merlot and Cabernet Franc, this win...",86,46.0,Washington,Columbia Valley (WA),Sean P. Sullivan,@wawinereport,Basel Cellars 2013 Inspired Red (Columbia Vall...,Bordeaux-style Red Blend,Basel Cellars
27,US,"Very deep in color and spicy-smoky in flavor, ...",86,12.0,California,California,Jim Gordon,@gordone_cellars,Cocobon 2014 Red (California),Red Blend,Cocobon
28,US,"Aromas of vanilla, char and toast lead to ligh...",86,12.0,Washington,Columbia Valley (WA),Sean P. Sullivan,@wawinereport,Drumheller 2014 Chardonnay (Columbia Valley (WA)),Chardonnay,Drumheller
29,US,Big oak defines this robustly dense and extrac...,86,40.0,California,Alexander Valley,Virginie Boone,@vboone,Eco Terreno 2013 Old Vine Cabernet Sauvignon (...,Cabernet Sauvignon,Eco Terreno
30,US,"Juicy plum, raspberry and pencil lead lead the...",86,75.0,California,Howell Mountain,Virginie Boone,@vboone,Hindsight 2013 Bella Vetta Vineyard Cabernet S...,Cabernet Sauvignon,Hindsight
31,US,This is the producer's first release of this w...,86,55.0,California,Calistoga,Virginie Boone,@vboone,Hindsight 2012 Estate Grown Petite Sirah (Cali...,Petite Sirah,Hindsight
32,US,This is made from equal parts Cabernet Franc a...,86,75.0,California,Napa Valley,Virginie Boone,@vboone,Mulvane Wine Co. 2013 The Cypher Red (Napa Val...,Bordeaux-style Red Blend,Mulvane Wine Co.
33,US,Some rosés are made simply by bleeding the jui...,86,25.0,Oregon,Eola-Amity Hills,Paul Gregutt,@paulgwine,Z'IVO 2015 Rosé of Pinot Noir (Eola-Amity Hills),Pinot Noir,Z'IVO
34,US,A healthy addition of 13% Petite Sirah provide...,86,24.0,California,Napa Valley,Virginie Boone,@vboone,Napa Cellars 2014 Classic Zinfandel (Napa Valley),Zinfandel,Napa Cellars
35,US,"Vibrant aromas of ripe pear, white flowers and...",86,20.0,Washington,Ancient Lakes,Sean P. Sullivan,@wawinereport,Palencia 2016 Albariño (Ancient Lakes),Albariño,Palencia
36,US,"Softened tannins surround a light-bodied, lean...",86,55.0,California,Knights Valley,Virginie Boone,@vboone,Passaggio 2014 Blau Vineyards Merlot (Knights ...,Merlot,Passaggio
37,US,"This blend of Sangiovese, Malbec, Cabernet Sau...",88,23.0,California,Sonoma County,Virginie Boone,@vboone,Ferrari-Carano 2014 Siena Red (Sonoma County),Red Blend,Ferrari-Carano
38,US,This wine has a touch of perceptible sweetness...,88,18.0,California,Sonoma Coast,Virginie Boone,@vboone,Folie à Deux 2015 Pinot Gris (Sonoma Coast),Pinot Gris,Folie à Deux
39,US,All red Bordeaux varieties are represented in ...,88,55.0,California,Napa Valley,Virginie Boone,@vboone,Franciscan 2013 Magnificat Meritage (Napa Valley),Meritage,Franciscan
...,...,...,...,...,...,...,...,...,...,...,...
50423,US,Earthy forest floor and Asian spice ride atop ...,90,25.0,California,Green Valley,Virginie Boone,@vboone,River Road 2014 Stephanie's Cuvée Pinot Noir (...,Pinot Noir,River Road
50424,US,This wine is a blend of Cabernet Sauvignon (40...,90,36.0,Washington,Yakima Valley,Sean P. Sullivan,@wawinereport,Stevens 2013 Stevens424 Red (Yakima Valley),Bordeaux-style Red Blend,Stevens
50425,US,Cabernet Sauvignon (84%) makes up the majority...,90,78.0,Washington,Columbia Valley (WA),Sean P. Sullivan,@wawinereport,Tenor 2012 1:1 Red (Columbia Valley (WA)),Bordeaux-style Red Blend,Tenor
50426,US,This wine is made from a field blend that incl...,90,36.0,California,Russian River Valley,Virginie Boone,@vboone,Acorn 2013 Alegria Vineyards Axiom Syrah (Russ...,Syrah,Acorn
50427,US,"This wine hits the mark, combining intriguing ...",90,25.0,California,California,Jim Gordon,@gordone_cellars,Biltmore Estate NV Brut Sparkling (California),Sparkling Blend,Biltmore Estate
50428,US,Almost like liquid cherry piebut not sweetth...,90,32.0,California,Anderson Valley,Jim Gordon,@gordone_cellars,Brutocao 2013 Slow Lope'n Vineyard Pinot Noir ...,Pinot Noir,Brutocao
50430,US,Lemon-lime soda aromas meet with orange blosso...,91,25.0,California,Santa Ynez Valley,Matt Kettmann,@mattkettmann,Zaca Mesa 2013 Roussanne (Santa Ynez Valley),Roussanne,Zaca Mesa
50431,US,"Round red cherry, deep plum and ripe cranberry...",91,34.0,California,Santa Lucia Highlands,Matt Kettmann,@mattkettmann,August West 2015 Pinot Noir (Santa Lucia Highl...,Pinot Noir,August West
50432,US,"Chocolate, mocha and coconut notes highlight t...",91,100.0,California,Calistoga,Virginie Boone,@vboone,Jax 2013 Estate Block 3 Cabernet Sauvignon (Ca...,Cabernet Sauvignon,Jax
50433,US,A blend of vineyards including the winery's Mi...,91,30.0,California,Green Valley,Virginie Boone,@vboone,Martin Ray 2015 Limited Release Chardonnay (Gr...,Chardonnay,Martin Ray
50434,US,"Smoothly seductive in texture and body, this m...",91,36.0,California,Alexander Valley,Virginie Boone,@vboone,Mazzocco 2014 Stuhlmuller Vineyard Reserve Cha...,Chardonnay,Mazzocco
50435,US,"This hearty, rich bottling needs time to breat...",91,48.0,California,Paso Robles,Matt Kettmann,@mattkettmann,MCV 2014 Petite Sirah (Paso Robles),Petite Sirah,MCV
50436,US,Plum and cherry fruit show on the nose of this...,91,52.0,California,Paso Robles,Matt Kettmann,@mattkettmann,Midnight 2012 Mare Nectaris Reserve Red (Paso ...,Bordeaux-style Red Blend,Midnight
50437,US,"Aged entirely in stainless steel, this combine...",91,30.0,California,Napa Valley,Virginie Boone,@vboone,Paraduxx 2015 Proprietary White (Napa Valley),White Blend,Paraduxx
50438,US,"A blend of Sauvignon Blanc, Sauvignon Gris and...",91,33.0,California,Chalk Hill,Virginie Boone,@vboone,Chalk Hill 2015 Estate Bottled Sauvignon Blanc...,Sauvignon Blanc,Chalk Hill
50439,US,Pencil shaving and graphite notes lend a class...,91,35.0,California,Napa Valley,Virginie Boone,@vboone,Conn Creek 2013 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Conn Creek
50440,US,"Hailing from an extreme coastal vineyard, this...",91,20.0,California,San Luis Obispo County,Matt Kettmann,@mattkettmann,Derby 2015 Derbyshire Vineyard Pinot Gris (San...,Pinot Gris,Derby
50441,US,From the Ranch House block of the famous viney...,91,55.0,California,Sonoma Coast,Virginie Boone,@vboone,Dunstan 2014 Durell Vineyard Pinot Noir (Sonom...,Pinot Noir,Dunstan
50443,US,"The third vintage of Mith is the best yet, com...",91,40.0,Washington,Columbia Valley (WA),Paul Gregutt,@paulgwine,Balboa 2005 Mith Red Wine Red (Columbia Valley...,Red Blend,Balboa
50444,US,"This ripe, rich, almost decadently thick wine ...",91,105.0,Washington,Walla Walla Valley (WA),Paul Gregutt,@paulgwine,Nicholas Cole Cellars 2004 Reserve Red (Walla ...,Red Blend,Nicholas Cole Cellars
50446,US,This pure Syrah from Reininger's estate vineya...,91,41.0,Washington,Walla Walla Valley (WA),Paul Gregutt,@paulgwine,Reininger 2005 Ash Hollow Vineyard Syrah (Wall...,Syrah,Reininger
50447,US,"It's 100% Cabernet Franc, a delightful, bright...",91,28.0,Washington,Columbia Valley (WA),Paul Gregutt,@paulgwine,Tamarack Cellars 2006 Cabernet Franc (Columbia...,Cabernet Franc,Tamarack Cellars
50448,US,"This has lovely raspberry and cranberry fruit,...",91,38.0,Washington,Columbia Valley-Walla Walla Valley,Paul Gregutt,@paulgwine,Va Piano 2006 Syrah (Columbia Valley-Walla Wal...,Syrah,Va Piano
50450,US,"A Chardonnay with an unusual companion, 8% Sém...",90,20.0,California,Mendocino County,Virginie Boone,@vboone,Apriori 2013 Chardonnay (Mendocino County),Chardonnay,Apriori
50451,US,This is classic in herbaceous aromas and flavo...,90,35.0,California,Sonoma County,Virginie Boone,@vboone,Arrowood 2010 Cabernet Sauvignon (Sonoma County),Cabernet Sauvignon,Arrowood
50452,US,Hailing from one of the more popular vineyards...,90,20.0,California,Santa Ynez Valley,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
50453,US,There's no bones about the use of oak in this ...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
50454,US,This opens with herbaceous dollops of thyme an...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry
50455,US,This Zinfandel from the eastern section of Nap...,90,22.0,California,Chiles Valley,Virginie Boone,@vboone,Houdini 2011 Zinfandel (Chiles Valley),Zinfandel,Houdini
50456,US,Citation is given as much as a decade of bottl...,90,75.0,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [64]:
wine_df.count()

country                  50457
description              50457
points                   50457
price                    50238
province                 50457
region_1                 50202
taster_name              34466
taster_twitter_handle    31749
title                    50457
variety                  50457
winery                   50457
dtype: int64

In [54]:
# replace the empty strings with np.nan objects
wine_df['region_1'].replace('', np.nan, inplace=True)
wine_df.tail()

,country,description,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery
50452,US,Hailing from one of the more popular vineyards...,90,20.0,California,Santa Ynez Valley,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
50453,US,There's no bones about the use of oak in this ...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
50454,US,This opens with herbaceous dollops of thyme an...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry
50455,US,This Zinfandel from the eastern section of Nap...,90,22.0,California,Chiles Valley,Virginie Boone,@vboone,Houdini 2011 Zinfandel (Chiles Valley),Zinfandel,Houdini
50456,US,Citation is given as much as a decade of bottl...,90,75.0,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [55]:
# dropping rows based on the NaN 'region_1' values 
wine_df.dropna(subset=['region_1'], inplace=True)

In [56]:
wine_df.count()

country                  50202
description              50202
points                   50202
price                    49985
province                 50202
region_1                 50202
taster_name              34230
taster_twitter_handle    31527
title                    50202
variety                  50202
winery                   50202
dtype: int64

In [57]:
# replace the empty strings with np.nan objects in price column
wine_df['price'].replace('', np.nan, inplace=True)
wine_df.tail()

,country,description,points,price,province,region_1,taster_name,taster_twitter_handle,title,variety,winery
50452,US,Hailing from one of the more popular vineyards...,90,20.0,California,Santa Ynez Valley,Matt Kettmann,@mattkettmann,Birichino 2013 Jurassic Park Vineyard Old Vine...,Chenin Blanc,Birichino
50453,US,There's no bones about the use of oak in this ...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Flora Springs 2013 Barrel Fermented Chardonnay...,Chardonnay,Flora Springs
50454,US,This opens with herbaceous dollops of thyme an...,90,35.0,California,Napa Valley,Virginie Boone,@vboone,Hendry 2012 Blocks 7 & 22 Zinfandel (Napa Valley),Zinfandel,Hendry
50455,US,This Zinfandel from the eastern section of Nap...,90,22.0,California,Chiles Valley,Virginie Boone,@vboone,Houdini 2011 Zinfandel (Chiles Valley),Zinfandel,Houdini
50456,US,Citation is given as much as a decade of bottl...,90,75.0,Oregon,Oregon,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation

In [69]:
# dropping rows based on the NaN 'price' values 
wine_df.dropna(subset=['price'], inplace=True)

In [70]:
wine_df.count()

country                  49985
description              49985
points                   49985
price                    49985
province                 49985
region_1                 49985
taster_name              34032
taster_twitter_handle    31342
title                    49985
variety                  49985
winery                   49985
dtype: int64

In [58]:
wine_df = wine_df.drop(['taster_name','taster_twitter_handle'],axis=1)

In [59]:
wine_df.count()

country        50202
description    50202
points         50202
price          49985
province       50202
region_1       50202
title          50202
variety        50202
winery         50202
dtype: int64

In [60]:
regions = wine_df['region_1'].unique()
len(regions)

264

In [61]:
variety = wine_df['variety'].unique()

In [62]:
len(variety)

256

In [63]:

regions_df = pd.DataFrame({'region_1':regions,'lat':"",'lon':""})

In [64]:
regions_df.head()

  lat lon             region_1
0            Willamette Valley
1          Lake Michigan Shore
2                  Napa Valley
3             Alexander Valley
4                Central Coast

In [108]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()

In [109]:
for index,row in regions_df.iterrows():
    try:
        location = geolocator.geocode(row["region_1"],timeout=10)
        lat = location.latitude
        lon = location.longitude
    
        regions_df.set_value(index,"lat",lat)
        regions_df.set_value(index,"lon",lon)
    except AttributeError:
        print("oops!! missing region_1 values")

oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values
oops!! missing region_1 values

In [65]:
regions_df.head()
# regions_df.to_csv('regions.csv',encoding='utf-8')

  lat lon             region_1
0            Willamette Valley
1          Lake Michigan Shore
2                  Napa Valley
3             Alexander Valley
4                Central Coast

In [149]:
# read the csv files into pandas as dataframes
filepath = os.path.join("regions.csv")
my_regions_df = pd.read_csv(filepath,encoding='utf-8')

In [68]:
my_regions_df.head()

   Unnamed: 0        lat         lon             region_1
0           0  45.344287 -122.667037    Willamette Valley
1           1  42.764927  -83.497657  Lake Michigan Shore
2           2  22.411245  113.980393          Napa Valley
3           3  37.180153  -89.350283     Alexander Valley
4           4 -33.311710  151.312067        Central Coast

In [69]:
#drop the 'Unnames: 0' column
my_regions_df = my_regions_df.drop(['Unnamed: 0'],axis=1)

In [70]:
my_regions_df.head()

         lat         lon             region_1
0  45.344287 -122.667037    Willamette Valley
1  42.764927  -83.497657  Lake Michigan Shore
2  22.411245  113.980393          Napa Valley
3  37.180153  -89.350283     Alexander Valley
4 -33.311710  151.312067        Central Coast

In [71]:
# replace the empty strings with np.nan objects in 'lat' and 'lon' columns of regions_df dataframe
my_regions_df['lat'].replace('', np.nan, inplace=True)

In [72]:
my_regions_df['lon'].replace('', np.nan, inplace=True)

In [73]:
my_regions_df

           lat         lon                                       region_1
0    45.344287 -122.667037                              Willamette Valley
1    42.764927  -83.497657                            Lake Michigan Shore
2    22.411245  113.980393                                    Napa Valley
3    37.180153  -89.350283                               Alexander Valley
4   -33.311710  151.312067                                  Central Coast
5    37.123224  -78.492772                                       Virginia
6    43.979280 -120.737257                                         Oregon
7    35.626765 -120.691246                                    Paso Robles
8    38.416990 -123.099029                                   Sonoma Coast
9    39.280645  -80.344534                                     Clarksburg
10   49.231853 -124.764732                               Dry Creek Valley
11   37.821287  -85.969915                                  Sonoma Valley
12   45.210984 -123.197585                                    McMinnville
13   42.332599  -87.993985                                    Lake County
14   38.010328  -78.452344                                     Monticello
15  -23.005356  -43.329795                                    North Coast
16   46.294766 -117.917470                           Columbia Valley (WA)
17   34.608637 -120.104677                              Santa Ynez Valley
18   36.701463 -118.755997                                     California
19   38.580219 -122.431384                                Howell Mountain
20   38.578797 -122.579705                                      Calistoga
21         NaN         NaN                               Eola-Amity Hills
22   41.947247  -88.399782                                  Ancient Lakes
23   53.013841   -1.358473                                 Knights Valley
24   38.511080 -122.847339                                  Sonoma County
25   39.621490  -84.196509                                   Finger Lakes
26   39.021301  -84.555223                             Santa Clara Valley
27   38.395445 -122.360173                                     Yountville
28   30.705979 -104.214914                                       Rockpile
29         NaN         NaN                          Santa Lucia Highlands
..         ...         ...                                            ...
234        NaN         NaN                        Napa County-Lake County
235  34.395342 -111.763275                                        Arizona
236  38.297137 -122.285529                                           Napa
237  38.000000 -121.400000                                 Central Valley
238        NaN         NaN                        Napa-Monterey-Mendocino
239  39.154274  -76.955809                               Lime Kiln Valley
240        NaN         NaN                                    Amador-Napa
241  27.944854  -81.726879                                    Polk County
242        NaN         NaN      Monterey County-Napa County-Sonoma County
243        NaN         NaN  Antelope Valley of the California High Desert
244        NaN         NaN                        Napa Valley-Paso Robles
245        NaN         NaN                      Lake County-Sonoma County
246        NaN         NaN                               Mendocino-Amador
247        NaN         NaN                                    Napa-Amador
248        NaN         NaN          Napa County-Sonoma County-Lake County
249  37.050096 -121.990591                              Santa Cruz County
250        NaN         NaN                 Sonoma-Santa Barbara-Mendocino
251        NaN         NaN                          Napa-Mendocino-Sonoma
252  42.378877  -72.032366                                  Massachusetts
253        NaN         NaN                               Lake-Sonoma-Napa
254  41.721715  -82.820187                                Isle St. George
255  32.962456  -96.334328                                         Texoma
256  38.707681 -122.048027                                   Capay Valley
257        NaN         NaN                           Sonoma-Napa-Monterey
258  21.216044 -157.975203                                         Hawaii
259        NaN         NaN                    Monterey County-Napa County
260  32.963784 -116.770628                               San Diego County
261  43.241475  -79.846720                             Niagara Escarpment
262  38.293313 -122.469386                               Sonoma-Napa-Lake
263        NaN         NaN             Sonoma County-Santa Barbara County

[264 rows x 3 columns]

In [74]:
# create latitude and longitude columns in wine_df
wine_df['latitude']=''
wine_df['longitude']=''

In [75]:
wine_df.head()

,country,description,points,price,province,region_1,title,variety,winery,latitude,longitude
0,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,,
1,US,"Pineapple rind, lemon pith and orange blossom ...",87,13.0,Michigan,Lake Michigan Shore,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,,
2,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,,
3,US,"Soft, supple plum envelopes an oaky structure ...",87,19.0,California,Napa Valley,Kirkland Signature 2011 Mountain Cuvée Caberne...,Cabernet Sauvignon,Kirkland Signature,,
4,US,"Slightly reduced, this wine offers a chalky, t...",87,34.0,California,Alexander Valley,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,Cabernet Sauvignon,Louis M. Martini,,

In [76]:
my_regions_df.rename(columns={'lat': 'latitude','lon':'longitude'}, inplace=True)

In [77]:
my_regions_df.head()

    latitude   longitude             region_1
0  45.344287 -122.667037    Willamette Valley
1  42.764927  -83.497657  Lake Michigan Shore
2  22.411245  113.980393          Napa Valley
3  37.180153  -89.350283     Alexander Valley
4 -33.311710  151.312067        Central Coast

In [78]:
coord_df = pd.merge(wine_df, my_regions_df, on='region_1')

In [79]:

#drop the 'latitude_x' nad 'longitude_x' column
coord_df = coord_df.drop(['latitude_x','longitude_x'],axis=1)

In [80]:
coord_df.head()

,country,description,points,price,province,region_1,title,variety,winery,latitude_y,longitude_y
0,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,45.344287,-122.667037
1,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,45.344287,-122.667037
2,US,"A stiff, tannic wine, this slowly opens and br...",86,22.0,Oregon,Willamette Valley,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars,45.344287,-122.667037
3,US,This wine is bursting with gorgeous cherry fru...,91,38.0,Oregon,Willamette Valley,Le Cadeau 2014 Pinot Noir (Willamette Valley),Pinot Noir,Le Cadeau,45.344287,-122.667037
4,US,"There is an odd, piercing edge to the aromas, ...",85,28.0,Oregon,Willamette Valley,Silvan Ridge 2006 Reserve Pinot Noir (Willamet...,Pinot Noir,Silvan Ridge,45.344287,-122.667037

In [81]:
coord_df.rename(columns={'latitude_y': 'latitude','longitude_y':'longitude'}, inplace=True)

In [82]:
coord_df.head()

,country,description,points,price,province,region_1,title,variety,winery,latitude,longitude
0,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,45.344287,-122.667037
1,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,45.344287,-122.667037
2,US,"A stiff, tannic wine, this slowly opens and br...",86,22.0,Oregon,Willamette Valley,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars,45.344287,-122.667037
3,US,This wine is bursting with gorgeous cherry fru...,91,38.0,Oregon,Willamette Valley,Le Cadeau 2014 Pinot Noir (Willamette Valley),Pinot Noir,Le Cadeau,45.344287,-122.667037
4,US,"There is an odd, piercing edge to the aromas, ...",85,28.0,Oregon,Willamette Valley,Silvan Ridge 2006 Reserve Pinot Noir (Willamet...,Pinot Noir,Silvan Ridge,45.344287,-122.667037

In [83]:
coord_df['longitude'].replace('', np.nan, inplace=True)
coord_df['latitude'].replace('', np.nan, inplace=True)
coord_df.tail()

,country,description,points,price,province,region_1,title,variety,winery,latitude,longitude
50197,US,"This is this winery's fourth vintage, and the ...",89,32.0,California,San Diego County,Hungry Hawk 2016 Albariño (San Diego County),Albariño,Hungry Hawk,32.963784,-116.770628
50198,US,This bottling shows great promise for the San ...,91,52.0,California,San Diego County,2Plank 2014 Bonsall Cabernet Sauvignon (San Di...,Cabernet Sauvignon,2Plank,32.963784,-116.770628
50199,US,"Whiffs of damp soil and leather lend a rustic,...",86,25.0,New York,Niagara Escarpment,Freedom Run 2010 Estate Reserve Pinot Noir (Ni...,Pinot Noir,Freedom Run,43.241475,-79.846720
50200,US,"This is a stunning wine at this price, sourced...",91,20.0,California,Sonoma-Napa-Lake,Summers 2013 Andriana's Cuvee Cabernet Sauvign...,Cabernet Sauvignon,Summers,38.293313,-122.469386
50201,US,"A brisk, likeable Chardonnay. It shows ripe fl...",86,14.0,California,Sonoma County-Santa Barbara County,Angeline 2008 Reserve Chardonnay (Sonoma Count...,Chardonnay,Angeline,NaN,NaN

In [84]:
coord_df.to_csv('coordinates.csv',encoding='utf-8')

In [85]:
# group the wine_df absed on variety and region
grouped = coord_df.groupby(['variety','region_1'])

In [86]:
grouped = grouped['region_1'].count()

In [87]:
grouped

variety    region_1
Abouriou   Russian River Valley                  1
Aglianico  Amador County                         2
           California                            1
           Clear Lake                            1
           Dry Creek Valley                      1
           Kelsey Bench-Lake County              1
           Mendocino                             1
           Mendocino County                      1
           Paso Robles                           2
           Sierra Foothills                      2
           St. Helena                            1
           Texas                                 1
           Tuolumne County                       1
Albariño   Ancient Lakes                         2
           Anderson Valley                       1
           Arroyo Seco                           1
           Calaveras County                      5
           Carneros                              2
           Central Coast                         6
           Chehalem Mountains                    1
           Clarksburg                            1
           Clements Hills                        1
           Columbia Valley (WA)                  3
           Edna Valley                          23
           Horse Heaven Hills                    1
           Hudson River Region                   1
           Lodi                                  8
           Michigan                              1
           Monterey                              5
           Monterey County                       2
                                              ...
Zinfandel  Santa Cruz Mountains                  2
           Santa Margarita Ranch                 2
           Santa Ynez Valley                     1
           Shenandoah Valley (CA)               33
           Sierra Foothills                     20
           Solano County                         1
           Sonoma Coast                          5
           Sonoma County                       159
           Sonoma County-San Joaquin County      3
           Sonoma Mountain                       5
           Sonoma Valley                       124
           South Coast                           2
           St. Helena                           20
           Stags Leap District                   1
           Tehama County                         1
           Temecula                              1
           Temecula Valley                       3
           Templeton Gap District                1
           Texas                                 1
           Umpqua Valley                         1
           Wahluke Slope                         7
           Walla Walla Valley (WA)               3
           Washington                            2
           Yakima Valley                         1
           Yolo County                           2
Zweigelt   Columbia Valley (WA)                  1
           Finger Lakes                          1
           Naches Heights                        3
           Seneca Lake                           1
           Yakima Valley                         1
Name: region_1, Length: 3663, dtype: int64

In [88]:
# convert the grouped object to dataframe
variety_df = pd.DataFrame({'count' : coord_df.groupby( [ "variety", "region_1","latitude","longitude"] ).size()}).reset_index()
variety_df.head()

     variety              region_1   latitude   longitude  count
0   Abouriou  Russian River Valley  38.902859 -123.058111      1
1  Aglianico         Amador County  38.449089 -120.591102      2
2  Aglianico            California  36.701463 -118.755997      1
3  Aglianico            Clear Lake  44.759559  -96.682644      1
4  Aglianico      Dry Creek Valley  49.231853 -124.764732      1

In [92]:
# creating the geojson data for a grape variety chosen

geojson=[]
for index,row in variety_df.iterrows():
    feature = {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [row['latitude'],row['longitude']] 
        },
        "properties": {
            "name":row['region_1'],
            "grape":row['variety'],
            "count":row['count']
        }
    }
    geojson.append(feature)

geoJson_data = {
  "type": "FeatureCollection",
  "features": geojson
}

In [190]:
import json
with open('geoJson_data.txt', 'w') as outfile:
    json.dump(geoJson_data, outfile)

In [151]:
# read the csv files into pandas as dataframes
filepath = os.path.join("coordinates.csv")
cluster_df = pd.read_csv(filepath,encoding="iso-8859-1", low_memory=False)

In [144]:
cluster_df.head()

,Unnamed: 0,country,description,points,price,province,region_1,title,variety,winery,latitude,longitude
0,0,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,45.344287,-122.667037
1,1,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,45.344287,-122.667037
2,2,US,"A stiff, tannic wine, this slowly opens and br...",86,22.0,Oregon,Willamette Valley,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars,45.344287,-122.667037
3,3,US,This wine is bursting with gorgeous cherry fru...,91,38.0,Oregon,Willamette Valley,Le Cadeau 2014 Pinot Noir (Willamette Valley),Pinot Noir,Le Cadeau,45.344287,-122.667037
4,4,US,"There is an odd, piercing edge to the aromas, ...",85,28.0,Oregon,Willamette Valley,Silvan Ridge 2006 Reserve Pinot Noir (Willamet...,Pinot Noir,Silvan Ridge,45.344287,-122.667037

In [145]:
cluster= cluster_df.groupby(["region_1","latitude","longitude"]).agg({"variety":pd.Series.nunique}).reset_index()

In [146]:
cluster.head()

            region_1   latitude   longitude  variety
0  Adelaida District   4.653006  -74.055808       28
1   Alexander Valley  37.180153  -89.350283       35
2          Alta Mesa  37.398829 -122.134686        5
3      Amador County  38.449089 -120.591102       36
4      Ancient Lakes  41.947247  -88.399782       14

In [147]:
# create json dictionary from the above dataframe


json_data =[]
for index,row in cluster.iterrows():
   
    location = {
        "type": "Point",
        "coordinates": [row['latitude'],row['longitude']] ,
        "variety_count":row['variety'],
        "region":row['region_1']
    }
    json_data.append(location)

In [148]:
json_data

[{'coordinates': [4.65300645, -74.0558084894263],
  'type': 'Point',
  'variety_count': 28},
 {'coordinates': [37.1801529, -89.35028340000002],
  'type': 'Point',
  'variety_count': 35},
 {'coordinates': [37.398829, -122.13468590000002],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [38.449089, -120.5911018],
  'type': 'Point',
  'variety_count': 36},
 {'coordinates': [41.947247, -88.399782],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [40.11239970000001, -85.6657225],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [39.0007303, -120.9924431],
  'type': 'Point',
  'variety_count': 27},
 {'coordinates': [34.395342, -111.7632755],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [35.118586900000004, -120.5907252],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [21.4320532, -99.66683546670193],
  'type': 'Point',
  'variety_count': 22},
 {'coordinates': [38.4507431, -122.2627529],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [33.4709714, -81.9748429],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [33.72936370000001, -117.7793546],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [37.1309414, -122.1682351],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [43.1854085, -101.655263],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [38.255818100000006, -120.4981492],
  'type': 'Point',
  'variety_count': 27},
 {'coordinates': [36.7014631, -118.7559974],
  'type': 'Point',
  'variety_count': 69},
 {'coordinates': [39.3565832, -120.1821578],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [41.413524, -122.38486], 'type': 'Point', 'variety_count': 1},
 {'coordinates': [38.5787966, -122.5797054],
  'type': 'Point',
  'variety_count': 19},
 {'coordinates': [38.7076812, -122.0480266],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [36.4796839, -121.7324476],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [19.5286964, -96.9383067],
  'type': 'Point',
  'variety_count': 24},
 {'coordinates': [42.69767595, -76.71269026110251],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [-33.3117096, 151.312067495083],
  'type': 'Point',
  'variety_count': 46},
 {'coordinates': [38.0, -121.4], 'type': 'Point', 'variety_count': 3},
 {'coordinates': [34.1650086, -118.5795265],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [36.524006, -121.22862279999998],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [47.8012197, -120.6276904],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [0.8129871999999999, -77.8462929],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [36.7186762, -121.35436409999998],
  'type': 'Point',
  'variety_count': 12},
 {'coordinates': [39.2806451, -80.34453409999998],
  'type': 'Point',
  'variety_count': 21},
 {'coordinates': [44.7595585, -96.6826444421204],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [38.1907514, -121.0882767],
  'type': 'Point',
  'variety_count': 10},
 {'coordinates': [31.8514532, -109.8181858],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [32.020114, -102.713209],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [38.7251776, -105.6077167],
  'type': 'Point',
  'variety_count': 12},
 {'coordinates': [48.44476855, -123.391452311162],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [48.44476855, -123.391452311162],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [34.000749299999995, -81.03433129999998],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [45.9280203, -123.082293],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [46.2947665, -117.9174697],
  'type': 'Point',
  'variety_count': 79},
 {'coordinates': [37.9034806, -121.9175345],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [32.776853, -96.857517], 'type': 'Point', 'variety_count': 8},
 {'coordinates': [39.7556652, 9.67175329123376],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [14.6817584, 121.0331299],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [49.2318525, -124.7647323],
  'type': 'Point',
  'variety_count': 43},
 {'coordinates': [39.17165575, -94.5792892201309],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [34.420939700000005, -89.8270328],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [28.9785947, -96.6460877],
  'type': 'Point',
  'variety_count': 20},
 {'coordinates': [38.75741370000001, -120.5276129],
  'type': 'Point',
  'variety_count': 37},
 {'coordinates': [38.75741370000001, -120.5276129],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [39.8724467, -7.737414500000001],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [43.63705770000001, -123.5673843],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [38.5935173, -120.6604855],
  'type': 'Point',
  'variety_count': 21},
 {'coordinates': [38.5037966, -120.75548909999998],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [39.62149, -84.19650899999998],
  'type': 'Point',
  'variety_count': 49},
 {'coordinates': [38.5318041, -123.2178198],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [43.3670861, -80.31849770000002],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [48.4445864, 0.7736251000000001],
  'type': 'Point',
  'variety_count': 12},
 {'coordinates': [34.6216542, -118.4139702],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [38.792, -122.570971], 'type': 'Point', 'variety_count': 4},
 {'coordinates': [21.2160437, -157.975203],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [31.0826699, -98.5361482],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [38.5802188, -122.4313836],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [7.099221000000001, 125.5990937],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [40.5997415, -123.89977340000002],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [43.6447642, -114.0154071],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [40.0796319, -89.4339809],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [41.9216734, -93.3122705],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [41.7217149, -82.82018719999998],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [37.5726028, -85.1551411],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [53.01384105, -1.35847296847345],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [48.07858615, -120.475713837271],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [42.332599, -87.99398470000001],
  'type': 'Point',
  'variety_count': 37},
 {'coordinates': [42.1432445, -81.2396642041535],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [42.764927, -83.49765699999998],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [44.9236071, -85.51562829999997],
  'type': 'Point',
  'variety_count': 10},
 {'coordinates': [39.1542741, -76.9558093],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [37.6820583, -121.7680531],
  'type': 'Point',
  'variety_count': 34},
 {'coordinates': [45.3138959, 9.503263], 'type': 'Point', 'variety_count': 56},
 {'coordinates': [40.8517821, -73.0992277431],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [26.5288369, -108.96062240000002],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [29.34672835, -108.29439567237],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [34.03385755, -118.679064160789],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [38.0409144, -122.6199638],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [42.3788774, -72.03236600000002],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [37.3660757, -81.6478197],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [45.2109843, -123.1975851],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [39.3176491, -123.4126399],
  'type': 'Point',
  'variety_count': 39},
 {'coordinates': [39.3176491, -123.4126399],
  'type': 'Point',
  'variety_count': 41},
 {'coordinates': [39.3365545, -123.3011195],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [39.3176491, -123.4126399],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [39.6838155, -123.4786256],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [43.6211955, -84.6824346],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [38.9690189, -77.7355056],
  'type': 'Point',
  'variety_count': 17},
 {'coordinates': [38.7604815, -92.5617875],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [38.2551307, -121.4521395],
  'type': 'Point',
  'variety_count': 8},
 {'coordinates': [36.600256, -121.8946388],
  'type': 'Point',
  'variety_count': 32},
 {'coordinates': [36.2231079, -121.3877428],
  'type': 'Point',
  'variety_count': 36},
 {'coordinates': [34.421814000000005, -119.7269],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [-17.8014431, -63.2179591],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [38.01032755, -78.4523439044681],
  'type': 'Point',
  'variety_count': 24},
 {'coordinates': [36.6974604, -121.405214],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [38.3793566, -122.4477575],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [36.6974604, -121.405214],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [46.64095870000001, -120.6420137],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [38.2971367, -122.2855293],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [38.4898675, -122.3218414],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [22.41124455, 113.980393164403],
  'type': 'Point',
  'variety_count': 68},
 {'coordinates': [38.2582281, -122.30517],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [38.29331315, -122.469385870353],
  'type': 'Point',
  'variety_count': 6},
 {'coordinates': [38.2714335, -122.4236572],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [39.5158825, -116.8537227],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [39.3540335, -120.8089843],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [40.0757384, -74.4041622],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [34.5708167, -105.993007],
  'type': 'Point',
  'variety_count': 21},
 {'coordinates': [40.7306458, -73.9866136],
  'type': 'Point',
  'variety_count': 26},
 {'coordinates': [43.2414752, -79.84672040000002],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [35.6729639, -79.03929190000002],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [-23.0053563, -43.32979520000001],
  'type': 'Point',
  'variety_count': 34},
 {'coordinates': [38.5177297, -122.9738437],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [42.3037846, -122.9745456],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [43.447436, -79.66667199999998],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [40.2253569, -82.6881395],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [44.9576705, -85.5155287],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [43.9792797, -120.737257],
  'type': 'Point',
  'variety_count': 35},
 {'coordinates': [45.5625404, -122.6665296],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [36.7285708, -121.2785409],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [35.6267654, -120.6912456],
  'type': 'Point',
  'variety_count': 82},
 {'coordinates': [40.9699889, -77.72788309999999],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [38.8832359, -122.9938883],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [39.1012064, -120.7650606],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [27.9448537, -81.72687890000002],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [39.3221089, -123.113059],
  'type': 'Point',
  'variety_count': 10},
 {'coordinates': [47.8331514, -122.4345806],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [33.035378, -116.867513220741],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [45.0644539, -84.2652871],
  'type': 'Point',
  'variety_count': 23},
 {'coordinates': [31.473003, -93.831742],
  'type': 'Point',
  'variety_count': 17},
 {'coordinates': [35.35829670000001, -117.6167261],
  'type': 'Point',
  'variety_count': 39},
 {'coordinates': [39.2654449, -123.2044496],
  'type': 'Point',
  'variety_count': 13},
 {'coordinates': [29.5685388, -98.7033549],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [30.6857475, -84.8413087],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [30.705979100000004, -104.2149139],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [43.4725937, -71.6574492],
  'type': 'Point',
  'variety_count': 37},
 {'coordinates': [38.9028592, -123.0581113],
  'type': 'Point',
  'variety_count': 52},
 {'coordinates': [40.826489, -74.10680909999998],
  'type': 'Point',
  'variety_count': 20},
 {'coordinates': [29.4246002, -98.4951405],
  'type': 'Point',
  'variety_count': 6},
 {'coordinates': [36.6248089, -121.1177379],
  'type': 'Point',
  'variety_count': 19},
 {'coordinates': [43.03371660000001, -2.6574055],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [32.9637838, -116.7706277],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [37.708264, -122.280247],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [16.62792675, -92.7422107117313],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [35.2827525, -120.6596156],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [35.35402089999999, -120.3757163],
  'type': 'Point',
  'variety_count': 17},
 {'coordinates': [34.4221319, -119.7026673],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [34.7136533, -119.9858232],
  'type': 'Point',
  'variety_count': 54},
 {'coordinates': [34.421814000000005, -119.7269],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [37.2333253, -121.68463490000002],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [39.021301, -84.555223],
  'type': 'Point',
  'variety_count': 28},
 {'coordinates': [37.050096, -121.9905908],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [37.219111100000006, -122.0713502],
  'type': 'Point',
  'variety_count': 23},
 {'coordinates': [38.7752001, -119.0048097],
  'type': 'Point',
  'variety_count': 6},
 {'coordinates': [34.947792, -120.564712],
  'type': 'Point',
  'variety_count': 23},
 {'coordinates': [34.608637, -120.104677421497],
  'type': 'Point',
  'variety_count': 53},
 {'coordinates': [42.62798415, -76.8964140303032],
  'type': 'Point',
  'variety_count': 26},
 {'coordinates': [39.6725241, -75.5911629],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [31.536431300000004, -110.255489838222],
  'type': 'Point',
  'variety_count': 43},
 {'coordinates': [34.5134034, -118.3196305],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [46.1059546, -121.460637],
  'type': 'Point',
  'variety_count': 19},
 {'coordinates': [38.2218938, -121.9163555],
  'type': 'Point',
  'variety_count': 11},
 {'coordinates': [38.2529705, -122.1621917],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [31.6723455, -110.66195553057399],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [38.2866265, -122.434122634259],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [38.41699000000001, -123.099028645174],
  'type': 'Point',
  'variety_count': 26},
 {'coordinates': [38.5110803, -122.8473388],
  'type': 'Point',
  'variety_count': 45},
 {'coordinates': [38.3229698, -122.5749837],
  'type': 'Point',
  'variety_count': 18},
 {'coordinates': [37.8212867, -85.9699148],
  'type': 'Point',
  'variety_count': 43},
 {'coordinates': [38.4410844, -122.7144795],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [38.29331315, -122.469385870353],
  'type': 'Point',
  'variety_count': 7},
 {'coordinates': [38.29331315, -122.469385870353],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [22.2493255, 114.14950835],
  'type': 'Point',
  'variety_count': 21},
 {'coordinates': [51.4380491, 0.0693756825425191],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [42.1867143, -122.696902069014],
  'type': 'Point',
  'variety_count': 28},
 {'coordinates': [53.7748716, -122.00988490000002],
  'type': 'Point',
  'variety_count': 14},
 {'coordinates': [-15.9686862, -5.7129557],
  'type': 'Point',
  'variety_count': 21},
 {'coordinates': [14.5604833, 121.042489],
  'type': 'Point',
  'variety_count': 17},
 {'coordinates': [38.2339528, -122.12655490000002],
  'type': 'Point',
  'variety_count': 16},
 {'coordinates': [37.109548, -79.164799], 'type': 'Point', 'variety_count': 5},
 {'coordinates': [40.1251334, -122.2015529],
  'type': 'Point',
  'variety_count': 1},
 {'coordinates': [33.4946353, -117.1473661],
  'type': 'Point',
  'variety_count': 15},
 {'coordinates': [33.4946353, -117.1473661],
  'type': 'Point',
  'variety_count': 36},
 {'coordinates': [31.8160381, -99.5120986],
  'type': 'Point',
  'variety_count': 28},
 {'coordinates': [29.6642381, -98.1444271],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [32.962456, -96.334328], 'type': 'Point', 'variety_count': 1},
 {'coordinates': [51.3854486, -0.2379296],
  'type': 'Point',
  'variety_count': 9},
 {'coordinates': [38.056944, -119.9919351],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [43.3654703, -123.468541],
  'type': 'Point',
  'variety_count': 31},
 {'coordinates': [34.4458248, -119.0779359],
  'type': 'Point',
  'variety_count': 3},
 {'coordinates': [44.5990718, -72.5002608],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [37.1232245, -78.4927721],
  'type': 'Point',
  'variety_count': 43},
 {'coordinates': [46.7206936, -119.3980773],
  'type': 'Point',
  'variety_count': 32},
 {'coordinates': [45.99798079999999, -118.3989894],
  'type': 'Point',
  'variety_count': 19},
 {'coordinates': [38.8949549, -77.03664559999999],
  'type': 'Point',
  'variety_count': 47},
 {'coordinates': [45.3442868, -122.6670374],
  'type': 'Point',
  'variety_count': 28},
 {'coordinates': [36.0223527, -81.4900963],
  'type': 'Point',
  'variety_count': 4},
 {'coordinates': [46.601557, -120.5108421],
  'type': 'Point',
  'variety_count': 57},
 {'coordinates': [45.2298399, -123.2180414],
  'type': 'Point',
  'variety_count': 2},
 {'coordinates': [38.7184542, -121.9059001],
  'type': 'Point',
  'variety_count': 25},
 {'coordinates': [35.546083, -120.8332336],
  'type': 'Point',
  'variety_count': 5},
 {'coordinates': [38.395445, -122.36017255050601],
  'type': 'Point',
  'variety_count': 10}]

In [3]:
# Import Dependencies
import os
import numpy as np
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine,func

In [4]:
#################################################
# Database Setup
#################################################
dbfile = os.path.join('wine_reviews.sqlite')
engine = create_engine(f"sqlite:///{dbfile}")
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)
# Save references to each table
wine_reviews = Base.classes.reviews 
# Create our session (link) from Python to the Database
session = Session(engine)

AttributeError: reviews

In [8]:
# Query for the number of wine reviews by state
stmt = session.query(wine_reviews).statement
df = pd.read_sql_query(stmt, session.bind)

# df.set_index('province', inplace=True)

In [9]:
df.head()

,id,country,description,points,price,province,region_1,title,variety,winery,latitude,longitude
0,1,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Willamette Valley,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,45.344287,-122.667037
1,2,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Willamette Valley,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,45.344287,-122.667037
2,3,US,"A stiff, tannic wine, this slowly opens and br...",86,22.0,Oregon,Willamette Valley,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,Pinot Noir,Hawkins Cellars,45.344287,-122.667037
3,4,US,This wine is bursting with gorgeous cherry fru...,91,38.0,Oregon,Willamette Valley,Le Cadeau 2014 Pinot Noir (Willamette Valley),Pinot Noir,Le Cadeau,45.344287,-122.667037
4,5,US,"There is an odd, piercing edge to the aromas, ...",85,28.0,Oregon,Willamette Valley,Silvan Ridge 2006 Reserve Pinot Noir (Willamet...,Pinot Noir,Silvan Ridge,45.344287,-122.667037

In [10]:
cluster_df = df.groupby(["region_1","latitude","longitude"]).agg({"variety":pd.Series.nunique}).reset_index()

In [11]:
cluster_df.head()

            region_1   latitude   longitude  variety
0  Adelaida District   4.653006  -74.055808       28
1   Alexander Valley  37.180153  -89.350283       35
2          Alta Mesa  37.398829 -122.134686        5
3      Amador County  38.449089 -120.591102       36
4      Ancient Lakes  41.947247  -88.399782       14

In [12]:
# create json dictionary from the above dataframe


json_data =[]
for index,row in cluster_df.iterrows():
   
    location = {
        "type": "Point",
        "coordinates": [row['latitude'],row['longitude']] ,
        "variety_count":row['variety'],
        "region":row['region_1']
    }
    json_data.append(location)

In [ ]:
cluster_df.sort_values(by='points', ascending=False)